export const MenuEvents = {
  NEW: 'menu-new',
  OPEN: 'menu-open',
  OPEN_FOLDER: 'menu-open-folder',
  REVEAL_FILE: 'menu-reveal-file',
  SAVE: 'menu-save',
  SAVE_AS: 'menu-save-as',
  EXPORT_HTML: 'menu-export-html',
  UNDO: 'menu-undo',
  REDO: 'menu-redo',
  FIND: 'menu-find',
  FIND_REPLACE: 'menu-find-replace',
  IMAGE_STORAGE_BASE64: 'menu-image-storage-base64',
  IMAGE_STORAGE_LOCAL: 'menu-image-storage-local',
  IMAGE_STORAGE_URL: 'menu-image-storage-url',
  SYNC_FILE: 'menu-sync-file',
  MARK_SYNC: 'menu-mark-sync',
  TOGGLE_SIDEBAR: 'menu-toggle-sidebar',
  TOGGLE_THEME: 'menu-toggle-theme',
  TOGGLE_FULLSCREEN: 'menu-toggle-fullscreen',
  LANG_EN: 'menu-lang-en',
  LANG_ZH: 'menu-lang-zh',
  SETTINGS: 'menu-settings',
  ABOUT: 'menu-about',
} as const;

export type MenuEvent = typeof MenuEvents[keyof typeof MenuEvents];
